# 2 and 4 Beat Patterns (Knob)
beat_patterns = [
    "2Beat_Bass",
    "2Beat_BassSnare",
    "2Beat_FoxTrot1",
    "2Beat_FoxTrot2",
    "2Beat_Swing1",
    "2Beat_Swing2",
    "2Beat_March",
    "2Beat_Swing3",
    "2Beat_Parade",
    "2Beat_Shuffle",
    "4Beat_Bass",
    "4Beat_BassSnare",
    "4Beat_FoxTrot1",
    "4Beat_FoxTrot2",
    "4Beat_Swing1",
    "4Beat_Swing2",
    "4Beat_March",
    "4Beat_Swing3",
    "4Beat_Parade",
    "4Beat_Shuffle",
]

latin_patterns = [
    "Rhumba",
    "Beguine",
    "ChaCha",
    "Mambo1",
    "Mambo2",
    "Samba1",
    "Samba2",
    "Baion",
    "Merengue",
    "Bossa Nova",
    "Bolero",
    "Tango",
]

top_row_patterns = [
    "RockRoll1",
    "RockRoll2",
    "Dodompa",
    "SlowRock",
    "Ballad",
    "Western",
    "6_8_ March",
    "JazzWaltz",
    "Waltz",
]
